/*
exec pr_rptCuentasEmpresa_USD @ANIO=2020,@EMPRESA=N'sxper,PRPER',@IDREPORTE='DETXMES'
exec pr_rptCuentasEmpresa_USD @ANIO=2020,@mes=5,@EMPRESA=N'REFER',@IDREPORTE='RPTELA'
exec pr_rptCuentasEmpresa_USD @ANIO=2020,@EMPRESA=N'REFER',@IDREPORTE='RPTDGG'

exec pr_rptCuentasEmpresa_USD @ANIO=2021,@EMPRESA=N'sxper',@IDREPORTE='RPTELA'
exec pr_rptCuentasEmpresa_USD @ANIO=2020,@EMPRESA=N'sxper',@IDREPORTE='RPTEGN'
exec pr_rptCuentasEmpresa_USD @ANIO=2020,@EMPRESA=N'REFERVZLA',@IDREPORTE='RPTDR'
exec pr_rptCuentasEmpresa_USD @ANIO=2021,@EMPRESA=N'BALBS',@IDREPORTE='RPTDR'
select * from TEMPSALDOS order by 1,2
*/

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[pr_rptCuentasEmpresa_USD]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].pr_rptCuentasEmpresa_USD
 go
CREATE  PROCEDURE pr_rptCuentasEmpresa_USD 
(@ANIO		INT
,@EMPRESA   VARCHAR(100)
,@IDREPORTE VARCHAR(15)=''
,@MES		INT=12)
AS
BEGIN

	DECLARE @SQLSTR    NVARCHAR(MAX)='',@Parametro nvarchar(500)
	DECLARE @XEMP VARCHAR(15)
	DECLARE @FILTRO NVARCHAR(MAX)=' AND 1=1'
	
	DECLARE @ANIOANT INT=@ANIO-1


	DECLARE @INIPERIODO DATE=convert(date,CONCAT(CONVERT(CHAR(4),@ANIO)
						 ,RIGHT(CONCAT('0',RTRIM(CONVERT(CHAR(2),@MES))),2)
						 ,'01'))
	DECLARE @FINPERIODO DATE --=EOMONTH(@INIPERIODO)

	--tabla para llenar datos principales
	if exists(select 1 from sys.tables where name='TEMPSALDOS')
		drop table TEMPSALDOS;
		CREATE TABLE TEMPSALDOS (ANIO			INT
								,MES			INT
								,TRXDATE		DATE
								--,ACTINDX		INT --FOREIGN KEY REFERENCES GL00100(ACTINDX)
								,ACTDESCR		CHAR(50)
								,ACTNUMST		CHAR(20)
								,CURNCYID		CHAR(15)
								,SALDOBSF		NUMERIC(19,5)
								,SALDOUSD		NUMERIC(19,5)
								,NOTA			CHAR(20))
		CREATE INDEX idx_ACTNUMST ON TEMPSALDOS (ACTNUMST)
		--CREATE INDEX IDX_GRUPO ON TEMPSALDOS (ANIO,TRXDATE,ACTINDX)

	--cargar filtros tabla configuracion debo crear esta tabla 
	--FALTA MEJORAR ESTA SECCION
	IF (@IDREPORTE='DETXMES') SET @FILTRO=' AND LEFT(C.ACTNUMBR_1,1) between (''4'') and (''7'')'
	IF (@IDREPORTE='RPTELA')  SET @FILTRO=' AND LEFT(C.ACTNUMBR_1,3) IN (''612'',''714'') '
	IF (@IDREPORTE='RPTEGN')  SET @FILTRO=' AND LEFT(C.ACTNUMBR_1,3) IN (''713'')'
	IF (@IDREPORTE='RPTDGG')  SET @FILTRO=' AND LEFT(C.ACTNUMBR_1,3) IN (''612'',''711'',''712'',''713'',''714'')'
	IF (@IDREPORTE='RPTDR')   SET @FILTRO=' AND LEFT(C.ACTNUMBR_1,3) IN (''411'',''511'',''611'',''612'',''711'',''712'',''713'',''714'')'

	--balance general
	--IF (@IDREPORTE='RPTBGRAL')   SET @FILTRO=' AND LEFT(C.ACTNUMBR_1,1) between (''1'') and (''3'') AND LEFT(ACTNUMST,3) not in (''115'',''117'',''171'',''241'',''281'')'

	IF (@IDREPORTE='RPTGPR')  SET @FILTRO=' AND LEFT(C.ACTNUMBR_1,3) IN (''411'',''511'',''611'',''612'',''711'',''712'',''713'',''714'')'

	print  @FILTRO
	--cursor para poder consolidar las empresas
	DECLARE EMPRESAS CURSOR FOR   
	SELECT Value FROM dbo.Split(@EMPRESA,',')  WHERE VALUE<>''
	
    --BUSCAR E INSERTAR DE CADA EMPRESA
	OPEN EMPRESAS  
	FETCH NEXT FROM EMPRESAS INTO @XEMP   
	WHILE @@FETCH_STATUS = 0  
		BEGIN  
		--select @XEMP	
			SET @SQLSTR=@SQLSTR+'DECLARE @FECHAFP' + @XEMP +' DATE  = (SELECT TOP 1 EOMONTH(PERIODDT) from ' + @XEMP +'.dbo.SY40100  WHERE YEAR1=@ANIO AND SERIES=0 AND PERIODID=@FINPERIODO);  
			INSERT INTO TEMPSALDOS (ANIO,MES,TRXDATE,SALDOBSF,SALDOUSD,ACTDESCR,ACTNUMST,CURNCYID)
									SELECT ISNULL(HSTYEAR,@ANIO) ANIO,ISNULL(S.PERIODID,5) MES
									      ,ISNULL(S.TRXDATE,EOMONTH(CONCAT(@ANIO,''0501''))) TRXDATE
										  ,ISNULL(SUM(S.DEBITAMT - S.CRDTAMNT),0) SALDO
										  ,SUM(IIF(RTRIM(CURNCYID)=''USD'',S.ORDBTAMT - S.ORCRDAMT,0)) SALDOUSD	
										  ,MAX(RTRIM(ACTDESCR)) ACTDESCR
										  ,MAX(RTRIM(ACTNUMST)) ACTNUMST
										  ,ISNULL(CURNCYID,''USD'') CURNCYID
									  FROM ' + @XEMP +'.dbo.GL00100 C 
									  INNER JOIN ' + @XEMP +'.dbo.GL00105 D ON C.ACTINDX=D.ACTINDX
									   LEFT JOIN ' + @XEMP +'.dbo.GL30000 S ON C.ACTINDX=S.ACTINDX 
									   AND HSTYEAR IN (@ANIO,@ANIOX) AND S.TRXDATE<=@FECHAFP' + @XEMP +' -- AND S.PERIODID<=@FINPERIODO						  
									  WHERE LEFT(ACTNUMST,1)<>''4'' ' --año solicitado y anterior
										     + @FILTRO +									 	  
									 ' GROUP BY HSTYEAR,S.PERIODID,TRXDATE,C.ACTINDX,CURNCYID ;									 
									 INSERT INTO TEMPSALDOS (ANIO,MES,TRXDATE,SALDOBSF,SALDOUSD,ACTDESCR,ACTNUMST,CURNCYID,NOTA)
									SELECT ISNULL(HSTYEAR,@ANIO) ANIO,ISNULL(S.PERIODID,5) MES
										  ,ISNULL(S.TRXDATE,EOMONTH(CONCAT(@ANIO,''0501''))) TRXDATE
										  ,ISNULL(SUM(S.DEBITAMT - S.CRDTAMNT),0) SALDO
										  ,SUM(IIF(RTRIM(CURNCYID)=''USD'',S.ORDBTAMT - S.ORCRDAMT,0)) SALDOUSD										  
										  ,MAX(RTRIM(ACTDESCR)) ACTDESCR
										  ,MAX(RTRIM(ACTNUMST)) ACTNUMST
										  ,ISNULL(CURNCYID,''USD'') CURNCYID
										  ,ISNULL(SOP.USRDEF05,NULL)
									  FROM ' + @XEMP +'.dbo.GL00100 C 
									  INNER JOIN ' + @XEMP +'.dbo.GL00105 D ON C.ACTINDX=D.ACTINDX
									   LEFT JOIN ' + @XEMP +'.dbo.GL30000 S ON C.ACTINDX=S.ACTINDX AND HSTYEAR IN (@ANIO,@ANIOX)
												AND S.TRXDATE<=@FECHAFP' + @XEMP +' --  AND S.PERIODID<=@FINPERIODO			
									   LEFT JOIN ' + @XEMP +'.dbo.SOP10106 SOP ON S.ORCTRNUM=SOPNUMBE
									  WHERE LEFT(ACTNUMST,1)=''4'' ' --solo ventas para tomar el caso de refermat
										     + @FILTRO +									 	  
									 ' GROUP BY HSTYEAR,S.PERIODID,TRXDATE,C.ACTINDX,CURNCYID,ISNULL(SOP.USRDEF05,NULL) ;    
								 INSERT INTO TEMPSALDOS (ANIO,MES,TRXDATE,SALDOBSF,SALDOUSD,ACTDESCR,ACTNUMST,CURNCYID)
									SELECT ISNULL(OPENYEAR,@ANIO) ANIO,ISNULL(S.PERIODID,5) MES
										  ,ISNULL(S.TRXDATE,EOMONTH(CONCAT(@ANIO,''0501''))) TRXDATE
										  ,ISNULL(SUM(S.DEBITAMT - S.CRDTAMNT),0) SALDO
										  ,SUM(IIF(RTRIM(CURNCYID)=''USD'',S.ORDBTAMT - S.ORCRDAMT,0)) SALDOUSD	
										  ,MAX(RTRIM(ACTDESCR)) ACTDESCR
										  ,MAX(ACTNUMST) ACTNUMST
										  ,ISNULL(CURNCYID,''USD'') CURNCYID
									  FROM ' + @XEMP +'.dbo.GL00100 C 
									  INNER JOIN ' + @XEMP +'.dbo.GL00105 D ON C.ACTINDX=D.ACTINDX
									   LEFT JOIN ' + @XEMP +'.dbo.GL20000 S ON C.ACTINDX=S.ACTINDX AND OPENYEAR IN (@ANIO,@ANIOX) 
											AND S.TRXDATE<=@FECHAFP' + @XEMP +' -- AND S.PERIODID<=@FINPERIODO									  
									  WHERE LEFT(ACTNUMST,1)<>''4''  '
											 + @FILTRO +	
										'GROUP BY OPENYEAR,S.PERIODID,TRXDATE,C.ACTINDX,CURNCYID;
							INSERT INTO TEMPSALDOS (ANIO,MES,TRXDATE,SALDOBSF,SALDOUSD,ACTDESCR,ACTNUMST,CURNCYID,NOTA)
									SELECT ISNULL(OPENYEAR,@ANIO) ANIO,ISNULL(S.PERIODID,5) MES
									      ,ISNULL(S.TRXDATE,EOMONTH(CONCAT(@ANIO,''0501''))) TRXDATE
										  ,ISNULL(SUM(S.DEBITAMT - S.CRDTAMNT),0) SALDO
										  ,SUM(IIF(RTRIM(CURNCYID)=''USD'',S.ORDBTAMT - S.ORCRDAMT,0)) SALDOUSD
										  ,MAX(RTRIM(ACTDESCR)) ACTDESCR
										  ,MAX(ACTNUMST) ACTNUMST
										  ,ISNULL(CURNCYID,''USD'') CURNCYID
										  ,ISNULL(SOP.USRDEF05,NULL)
									  FROM ' + @XEMP +'.dbo.GL00100 C 
									  INNER JOIN ' + @XEMP +'.dbo.GL00105 D ON C.ACTINDX=D.ACTINDX
									   LEFT JOIN ' + @XEMP +'.dbo.GL20000 S ON C.ACTINDX=S.ACTINDX AND OPENYEAR IN (@ANIO,@ANIOX) 
											AND S.TRXDATE<=@FECHAFP' + @XEMP +' -- AND S.PERIODID<=@FINPERIODO	
									   LEFT JOIN ' + @XEMP +'.dbo.SOP10106 SOP ON S.ORCTRNUM=SOPNUMBE
										WHERE LEFT(ACTNUMST,1)=''4'' '
											 + @FILTRO +	
										'GROUP BY OPENYEAR,S.PERIODID,TRXDATE,C.ACTINDX,CURNCYID,ISNULL(SOP.USRDEF05,NULL);
									
										'			
			FETCH NEXT FROM EMPRESAS INTO @XEMP  
		END   
	CLOSE EMPRESAS;  
	DEALLOCATE EMPRESAS;

	SET @Parametro = N'@ANIO int,@ANIOX INT,@FINPERIODO INT';  
 PRINT @SQLSTR 
EXECUTE sp_executesql @SQLSTR, @Parametro,  
                      @ANIO = @ANIO,@ANIOX=@ANIOANT,@FINPERIODO=@MES	; 

	--select * from TEMPSALDOS;

END