/*
exec pr_rptELA_USD @ANIO=2021,@MONEDA=N'USD',@EMPRESA=N'REFER'
--se ejecuta en la BD principal, debe tener todas las cuentas contables.
*/

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[pr_rptELA_USD]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].pr_rptELA_USD
 go
CREATE  PROCEDURE pr_rptELA_USD 
(@ANIO		INT
,@MONEDA	VARCHAR(6)='USD' --1:GUARDA EN TABLAS,2: TABLAS TEMP PARA REPORTE
,@EMPRESA   VARCHAR(100)
,@MESPERIODO	INT=12)
AS
BEGIN

	DECLARE @TASA CHAR(15)=(SELECT TOP 1 TAXSCHID FROM BEF00200); --TASA DE CONVERSION 'USD REPORTE' 

--EJECUTA SP, PARA LLENAR TABLA CON SALDOS y aplicar filtros
	exec pr_rptCuentasEmpresa_USD @ANIO=@ANIO,@MES=@MESPERIODO,@EMPRESA=@EMPRESA,@IDREPORTE='RPTELA';
	--select * from TEMPSALDOS;

	 --AGRUPA LAS CUENTAS POR MES
	 WITH CTE_AGRUPO AS (	 
			 SELECT ANIO,MONTH(TRXDATE) MES,YEAR(TRXDATE) ANIOTRX
				   ,MAX(ACTDESCR) ACTDESCR
				   ,RTRIM(ACTNUMST) ACTNUMST
				   ,MAX(TRXDATE) TRXDATE
				   ,(SUM(SUM(SALDOBSF)) OVER (PARTITION BY ANIO,ACTNUMST ORDER BY ANIO,MONTH(TRXDATE))) ACUMBSF
			   FROM TEMPSALDOS
			  GROUP BY ANIO,YEAR(TRXDATE),MONTH(TRXDATE),ACTNUMST),
	  CTE_SALDOS AS(
		SELECT *
		,ACUMBSF/dbo.f_buscatasadia(EOMONTH(TRXDATE),@TASA) -
		        ISNULL((LAG(ACUMBSF/dbo.f_buscatasadia(EOMONTH(TRXDATE),@TASA))
				       OVER (PARTITION BY ANIO,ACTNUMST ORDER BY ANIO,MES)),0)	 SALDOUSD
		,ACUMBSF -
		        ISNULL((LAG(ACUMBSF)
				       OVER (PARTITION BY ANIO,ACTNUMST ORDER BY ANIO,MES)),0)	SALDOBSF
		 FROM CTE_AGRUPO
	  ),
	  CTE_CONFIG AS (
				   SELECT 'LIBERACIONES' GRUPO,'612' SEGMENTO
					UNION ALL
				   SELECT 'APARTADOS'	 GRUPO,'714' SEGMENTO
				  ) 

	   SELECT LEFT(ACTNUMST,3) SEGMENTO,ACTNUMST
	         ,ACTDESCR,ANIO,MES
			 ,IIF(@MONEDA='USD',SALDOUSD,SALDOBSF) SALDO
			 ,GRUPO
			 ,ANIOTRX
	   FROM CTE_SALDOS S
	  INNER JOIN CTE_CONFIG Z ON Z.SEGMENTO=LEFT(ACTNUMST,3) 
	  WHERE REPLACE(S.ACTNUMST,'-','') NOT IN ('714013001','714013004','714011047')
	  order by ACTNUMST,ANIO,MES
END