/*
exec pr_rptGBMayorDetallado_BSF @INIPERIODO='20210401',@FINPERIODO='20210531',@EMPRESA=N'PRPER',@CUENTAD='104-1100-02',@CUENTAH='104-1100-02'
TEMPSALDOSF order by actnumst,TRXDATE, curncyid


exec pr_rptGBMayorDetallado_BSF @INIPERIODO='20210501',@FINPERIODO='20210730',@EMPRESA=N'BALBS',@CUENTAD=N'',@CUENTAH=N'',@CONTABILIZADO=1
*/

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[pr_rptGBMayorDetallado_BSF]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].pr_rptGBMayorDetallado_BSF
 go
CREATE  PROCEDURE pr_rptGBMayorDetallado_BSF 
(@INIPERIODO	Date
,@FINPERIODO	Date
,@EMPRESA       VARCHAR(100)
,@CUENTAD		VARCHAR(30)='1'
,@CUENTAH		VARCHAR(30)='ZZZ'
,@CONTABILIZADO INT=1 --1 SI, 2 NO		
)
AS
BEGIN

	DECLARE @SQLSTR    NVARCHAR(MAX)='',@Parametro nvarchar(500)
	DECLARE @XEMP VARCHAR(15)
	DECLARE @FILTRO NVARCHAR(MAX)=' AND 1=1'

	DECLARE @TASA	   CHAR(15)=(SELECT TOP 1 TAXSCHID FROM BEF00200);  --TASA DE CONVERSION 'USD REPORTE'

	if (@CUENTAD='') SET @CUENTAD='1'
	if (@CUENTAH='') SET @CUENTAH='ZZZ'

	/*SELECT *,dbo.f_buscatasadia(TRXDATE,@TASA) TASA
	FROM TEMPSALDOSMD*/

	--EJECUTA SP, PARA LLENAR TABLA CON SALDOS y aplicar filtros
	exec pr_GBMayorDetallado_BSF @INIPERIODO=@INIPERIODO,@FINPERIODO=@FINPERIODO,@EMPRESA=@EMPRESA
	                            ,@CUENTAD=@CUENTAD,@CUENTAH=@CUENTAH,@CONTABILIZADO=@CONTABILIZADO;

	 WITH CTE_SALDO AS (
	 			   SELECT 
				       ACTNUMST
					  ,MAX(ACTDESCR) ACTDESCR
					  ,dateadd(day,-1,@INIPERIODO) TRXDATE
					  ,SUM(CASE WHEN PSTNGTYP=0 AND TRXDATE<@INIPERIODO THEN (DEBITAMT-CRDTAMNT)
								WHEN PSTNGTYP=1 AND TRXDATE<@INIPERIODO AND ANIO=YEAR(@FINPERIODO) 
								THEN (DEBITAMT-CRDTAMNT)
								ELSE 0 END) SALDO
					  ,SUM(CASE WHEN PSTNGTYP=0 AND TRXDATE<@INIPERIODO
								--THEN (ORDBTAMT-ORCRDAMT)--USD CREDITO / DEBITO
								THEN iif(CURNCYID='USD',ORDBTAMT-ORCRDAMT,convert(numeric(18,5),(DEBITAMT-CRDTAMNT)/dbo.f_buscatasadia(TRXDATE,@TASA)))---ORDBTAMT														
		  
																															
								WHEN PSTNGTYP=1 AND TRXDATE<@INIPERIODO AND ANIO=YEAR(@FINPERIODO) 
								--THEN (ORDBTAMT-ORCRDAMT)--USD CREDITO / DEBITO
								THEN iif(CURNCYID='USD',ORDBTAMT-ORCRDAMT,convert(numeric(18,5),(DEBITAMT-CRDTAMNT)/dbo.f_buscatasadia(TRXDATE,@TASA)))---ORDBTAMT
		  
																													
								ELSE 0 END) SALDOUSD
					  ,0 ORSALDO
				 FROM TEMPSALDOSMD 
				WHERE TRXDATE<@INIPERIODO
				GROUP BY ACTNUMST),
	  	  CTE_MOVIMIENTOS AS (
		   SELECT ANIO,PERIODID,JRNENTRY,TRXDATE,SOURCDOC,SDOCDSCR
					  ,ACTNUMST,ACTDESCR,DSCRIPTN,REFRENCE,ORDOCNUM
					  ,DEBITAMT,CRDTAMNT --BSF
					  --USD CREDITO / DEBITO
					  ,iif(CURNCYID='USD',ORDBTAMT,convert(numeric(18,5),ORDBTAMT/dbo.f_buscatasadia(TRXDATE,@TASA))) ORDBTAMT
					  ,iif(CURNCYID='USD',ORCRDAMT,convert(numeric(18,5),ORCRDAMT/dbo.f_buscatasadia(TRXDATE,@TASA))) ORCRDAMT					   
					  ,CURNCYID,PSTNGTYP,SUCURSAL,ORPSTDDT
		     FROM TEMPSALDOSMD
		    WHERE TRXDATE BETWEEN @INIPERIODO AND @FINPERIODO
		  ),
		  CTE_REPORTE AS (
			  SELECT   YEAR(TRXDATE) ANIO,'' PERIODID,0 JRNENTRY,TRXDATE,'SI' SOURCDOC
					  ,'Saldo Inicial' SDOCDSCR
					  ,ACTNUMST,ACTDESCR,'Saldo Inicial' DSCRIPTN,'Saldo Inicial' REFRENCE,'' ORDOCNUM
					  ,IIF(SALDO>=0 ,ABS(SALDO),0) DEBITAMT
					  ,IIF(SALDO<0,ABS(SALDO),0) CRDTAMNT
					  ,IIF(SALDOUSD>=0 ,ABS(SALDOUSD),0) ORDBTAMT	--USD CREDITO
					  ,IIF(SALDOUSD< 0 ,ABS(SALDOUSD),0) ORCRDAMT	--USD DEBITO
					  --,0 ORDBTAMT,0 ORCRDAMT
					  ,'' CURNCYID,0 PSTNGTYP
					  ,'' SUCURSAL
					  ,TRXDATE ORPSTDDT
			   FROM   CTE_SALDO
			   WHERE  SALDO<>0
			   UNION ALL 
			   SELECT  ANIO,PERIODID,JRNENTRY,TRXDATE,SOURCDOC,SDOCDSCR
					  ,ACTNUMST,ACTDESCR,DSCRIPTN,REFRENCE,ORDOCNUM
					  ,DEBITAMT,CRDTAMNT,ORDBTAMT,ORCRDAMT,CURNCYID,0 PSTNGTYP,SUCURSAL,ORPSTDDT	    
				 FROM CTE_MOVIMIENTOS
			)

			SELECT C.ANIO,C.PERIODID,C.JRNENTRY,C.TRXDATE,C.SOURCDOC,C.SDOCDSCR
					  ,C.ACTNUMST,C.ACTDESCR,C.DSCRIPTN,C.REFRENCE,C.ORDOCNUM
					  ,C.DEBITAMT,C.CRDTAMNT
					  ,C.ORDBTAMT,C.ORCRDAMT --USD CREDITO / DEBITO
					  ,IIF(SOURCDOC='SI',0,DEBITAMT) DEBMOVIENTO  --PARA EL TOTAL FINAL SIN SALDO INICIAL
					  ,IIF(SOURCDOC='SI',0,CRDTAMNT) CRDMOVIENTO  --PARA EL TOTAL FINAL SIN SALDO INICIAL
					  ,IIF(SOURCDOC='SI',0,ORDBTAMT) DEBMOVIENTOUSD  --PARA EL TOTAL FINAL SIN SALDO INICIAL USD CREDITO
					  ,IIF(SOURCDOC='SI',0,ORCRDAMT) CRDMOVIENTOUSD  --PARA EL TOTAL FINAL SIN SALDO INICIAL USD DEBITO
					  ,C.CURNCYID,C.PSTNGTYP,C.SUCURSAL,C.ORPSTDDT
			  ,I.UDCOSTR1 TSUCURSAL
			  FROM CTE_REPORTE C
			   LEFT JOIN DYNAMICS.dbo.SY01500 I ON C.SUCURSAL=I.INTERID
			 --ORDER BY ACTNUMST,JRNENTRY,TRXDATE

END