/*
exec pr_rptBalanceComp @ANIO=2021,@MES=1,@EMPRESA='REFER',@CUENTAD='1',@CUENTAH='6',@TIPO=3
exec pr_rptBalanceComp @ANIO=2021,@MES=1,@EMPRESA='REFER',@CUENTAD='1',@CUENTAH='6',@TIPO=2
exec pr_rptBalanceComp @ANIO=2021,@MES=1,@EMPRESA='REFER',@CUENTAD='1',@CUENTAH='7',@TIPO=1
--se ejecuta en la BD principal, debe tener todas las cuentas contables.
*/

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[pr_rptBalanceComp]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].pr_rptBalanceComp
 go
CREATE  PROCEDURE pr_rptBalanceComp 
(@ANIO		INT
,@MES		INT
,@EMPRESA   VARCHAR(100)
,@TIPO		VARCHAR(10)='1' --1DETALLE,2SUBGRUPO,3GRUPO
,@CUENTAD	VARCHAR(30)='1'
,@CUENTAH	VARCHAR(30)='ZZZ'

)
AS
BEGIN

	DECLARE @TASA	   CHAR(15)=(SELECT TOP 1 TAXSCHID FROM BEF00200);  --TASA DE CONVERSION 'USD REPORTE'    
	DECLARE @INIPERIODO DATE=convert(date,CONCAT(CONVERT(CHAR(4),@ANIO)
						 ,RIGHT(CONCAT('0',RTRIM(CONVERT(CHAR(2),@MES))),2)
						 ,'01'))
	DECLARE @FINPERIODO DATE=EOMONTH(@INIPERIODO)

	IF (@CUENTAD='' OR @CUENTAD IS NULL OR @CUENTAD='NULL') SET @CUENTAD='1'
    IF (@CUENTAH='' OR @CUENTAH IS NULL OR @CUENTAH='NULL') SET @CUENTAH='ZZZ'

--EJECUTA SP, PARA LLENAR TABLA CON SALDOS y aplicar filtros
	exec pr_CuentasFinancieroEmpresa_BSF @ANIO=@ANIO,@MES=@MES,@EMPRESA=@EMPRESA,@IDREPORTE='BALCOMP';
	--select * from TEMPSALDOS;
 print 'inicio';
	 --AGRUPA LAS CUENTAS POR MES
	 WITH CTE_SALDOS AS (
	 			   SELECT ACTNUMST
					  ,MAX(ACTDESCR) ACTDESCR
					  --,SUM(iif(TRXDATE<@INIPERIODO,(DEBITAMT-CRDTAMNT),0)) SALDOINICIAL
					  ,SUM(CASE WHEN PSTNGTYP=0 AND TRXDATE<@INIPERIODO THEN (DEBITAMT-CRDTAMNT)
								WHEN PSTNGTYP=1 AND TRXDATE<@INIPERIODO AND ANIO=@ANIO THEN (DEBITAMT-CRDTAMNT)
								ELSE 0 END) SALDOINICIAL
					  --,SUM(iif(TRXDATE<@INIPERIODO,(ORDBTAMT-ORCRDAMT),0)) SALDOINICIALUSD
					  ,SUM(CASE WHEN TRXDATE>=@INIPERIODO AND TRXDATE<=@FINPERIODO THEN DEBITAMT ELSE 0 END) DEBITAMT
					  ,SUM(CASE WHEN TRXDATE>=@INIPERIODO AND TRXDATE<=@FINPERIODO THEN CRDTAMNT ELSE 0 END) CRDTAMNT
					  --,SUM(CASE WHEN TRXDATE>=@INIPERIODO AND TRXDATE<=@FINPERIODO THEN ORDBTAMT ELSE 0 END) ORDBTAMT
					  --,SUM(CASE WHEN TRXDATE>=@INIPERIODO AND TRXDATE<=@FINPERIODO THEN ORCRDAMT ELSE 0 END) ORCRDAMT
					  ,SUM(DEBITAMT-CRDTAMNT)* 0 SALDOFINAL
					  --,SUM(DEBITAMT-CRDTAMNT) SALDOFINAL	
					  --,SUM(ORDBTAMT-ORCRDAMT) SALDOFINALUS
				 FROM TEMPSALDOSF 
				WHERE ACTNUMST BETWEEN @CUENTAD AND @CUENTAH
				GROUP BY ACTNUMST),
	  	  CTE_SUBGRUPO AS (
				SELECT SGMNTID,RTRIM(DSCRIPTN) DSCRIPTN FROM BEF00100 
		  ),
		  CTE_SEGMENTO AS (
					SELECT '1' ID,'ACTIVOS			   ' SEGMENTO UNION ALL
					SELECT '2' ID,'PASIVOS			   ' SEGMENTO UNION ALL
					SELECT '3' ID,'PATRIMONIO		   ' SEGMENTO UNION ALL
					SELECT '4' ID,'INGRESOS			   ' SEGMENTO UNION ALL
					SELECT '5' ID,'COSTOS			   ' SEGMENTO UNION ALL
					SELECT '6' ID,'INGRESOS MERCANTILES' SEGMENTO UNION ALL
					SELECT '7' ID,'GASTOS GENERALES	   ' SEGMENTO
		  )


	   SELECT CASE WHEN @TIPO=1 THEN ACTNUMST
				   WHEN @TIPO=2 THEN LEFT(REPLACE(ACTNUMST,'-',''),5)
				   WHEN @TIPO=3 THEN LEFT(REPLACE(ACTNUMST,'-',''),3) END GRUPO
			 ,CASE WHEN @TIPO=1 THEN ACTDESCR
				   WHEN @TIPO=2 THEN Y.DSCRIPTN
				   WHEN @TIPO=3 THEN G.DSCRIPTN END DESCRIPCION
	         ,ACTNUMST
			 ,ACTDESCR
			 ,E.ID SEGMENTO
	   		 ,SEGMENTO DESEGMENTO 
			 ,SALDOINICIAL
			 ,DEBITAMT,CRDTAMNT
			 ,(SALDOINICIAL+(DEBITAMT-CRDTAMNT)) SALDOFINAL
	   FROM CTE_SALDOS S
	   INNER JOIN CTE_SEGMENTO E ON LEFT(ACTNUMST,1)=E.ID
	   LEFT JOIN GL40200 G ON G.SGMNTID=LEFT(REPLACE(ACTNUMST,'-',''),3)
	   LEFT JOIN CTE_SUBGRUPO Y ON Y.SGMNTID=LEFT(REPLACE(ACTNUMST,'-',''),5) 
	   WHERE (ABS(SALDOINICIAL)+ABS(DEBITAMT)+ABS(CRDTAMNT))<>0
	   ORDER BY 1,ACTNUMST

END